apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-taller-k8s-diplomado
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-taller-k8s-diplomado
  template:
    metadata:
      labels:
        app: api-taller-k8s-diplomado
    spec:
      containers:
        - name: api-taller-k8s-diplomado
          image: joelvin/taller-k8s-diplomado:v2
          ports:
            - containerPort: 8080
