apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlOVEEwTVRFdwpNVEkzTlRkYUZ3MDBOVEEwTVRFd01USTNOVGRhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFDcVlNTnRmMnN6U3g0czgramhJOXk1enBzSVlqRFE2N1pESWFqa1BmZnNLNkJJY0ZTMwpPQ0RvbDR4WkdCV1pseC9lTzR6RG5TM2FQc1M0STN2WGFmTzdjcTNGZlVRU2NIK0ZlSVROd0ZvZWFZYktsMzNSCmVkSzF4ZE1SWlo2eThpajdOcHJnanZ6Y3AwTE5XYWJiL2xQaVBPazVJOEc2YnI4N0lVSEJ1TkF1UzlkdHMweDAKd2hVTnQzM2JaSU5GMjN6ZTB1TVlVZzRPaXVSNkt3UDlBYVdFSkVaVXB6Uk1NRFVCTlF4eVBKRitpYjRnWnUrOQo1OHFtd0dvMW1ObzVjSElyRVBLckprSWdYSXVLNnhtalBlVWgvZ3NSMmIwSHpQZ0gvTnkyQ0dhNWxkN2hqbFArCjZ4c0RtelI3aWlVNEF1RDV6MnBva3JKeHI3TGdHZm91SGU0M0FnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlFEVFJ2TXFkUVhqckhBcUJ4WQpWTUtEajl1L2l6QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFRNi9pODVBaGQyUjZNVUxlOVVMV0UvZVFhdktVCjQ4eFJVYlRiMTYyb3BmeTI2UDFkNlJlbWZ4OFBVdXQ1TVFmcFFsQXBoa0FGNk5uRmFJYlFYV1VubXdCMDRValQKUkIwRjAvY2JYS1kweVE1RlVMK29MTXJIUnFaVWQydXpLVG1XbzZuYnBFR3I1UXdmbzdqWktxQXlkcTVWaExuMQpZRGMrREZqamkzZEhidDhlUUtuRGd5SFdMRThvNVcyZHJZcFA0MDRNTHY1Q2dEUjVncTd5bzBUYm5rMGM5RmJzCi8vbUFoLy9iZVM2Wll6WjJPa3Ntek9Gb0lJTG83TXNhSlhpODdDcmlNZjZLeFZiVEtkdFdEUGxjZmxwQ3BFdkgKWDNiMWZlNEN6L2k5dkJqZEh2VjhoUXNWYnFiMTNYWFJIQkpGejVqcFovcGJUaEV6NC8rb0k1QktYUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      server: https://d0bea489-1dce-4fa3-ae88-df6407ce17a9.k8s.ondigitalocean.com
    name: do-lon1-k8s-1-32-2-do-0-lon1-1744334768173
contexts:
  - context:
      cluster: do-lon1-k8s-1-32-2-do-0-lon1-1744334768173
      user: do-lon1-k8s-1-32-2-do-0-lon1-1744334768173-admin
    name: do-lon1-k8s-1-32-2-do-0-lon1-1744334768173
current-context: do-lon1-k8s-1-32-2-do-0-lon1-1744334768173
kind: Config
preferences: {}
users:
  - name: do-lon1-k8s-1-32-2-do-0-lon1-1744334768173-admin
    user:
      token: dop_v1_69e3a95dfe93e2183219ac50a44479ad6deb95a88761bf3b9e027373ec86087b
