    apiVersion: v1
    kind: Service
    metadata:
      name: api-taller-k8s-diplomado-service
    spec:
      selector:
        app: api-taller-k8s-diplomado
      ports:
        - protocol: TCP
          port: 80
          targetPort: 8080
      type: LoadBalancer
