apiVersion: v1
kind: Service
metadata:
  name: taller-k8s-diplomado-service
spec:
  selector:
    app: taller-k8s-diplomado
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer