name: Deployment Kubernetes

on:
  push:
    branches:
      - master

env:
  REGISTRY: docker.io
  IMAGE_NAME: joelvin/taller-k8s-diplomado
  CHART_PATH: ./charts/taller-k8s-diplomado
  TAG_NAME: "v1"
  RELEASE_NAME: taller-k8s-diplomado
  NAMESPACE: default

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Debug variables
        run: |
          echo "RELEASE_NAME: $RELEASE_NAME"
          echo "TAG_NAME: $TAG_NAME"
          echo "CHART_PATH: $CHART_PATH"
          ls -la $CHART_PATH || echo "Chart path not found"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Test Maven
        run: mvn test
        working-directory: ./

      - name: Compile Maven
        run: mvn clean package -DskipTests
        working-directory: ./

      - name: Login en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build imagen Docker
        run: |
          docker build -t $REGISTRY/$IMAGE_NAME:$TAG_NAME .

      - name: Push imagen Docker
        run: |
          docker push $REGISTRY/$IMAGE_NAME:$TAG_NAME

      - name: Set up kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: '3.14.0'

      - name: Deploy with Helm
        run: |
          helm upgrade --install $RELEASE_NAME $CHART_PATH \
            --namespace $NAMESPACE \
            --set image.repository=$REGISTRY/$IMAGE_NAME \
            --set image.tag=$TAG_NAME

      - name: Deployment Status
        run: |
          kubectl rollout status deployment/$RELEASE_NAME -n $NAMESPACE --timeout=60s
          kubectl get all -n $NAMESPACE

      - name: POD Logs
        run: |
          POD_NAME=$(kubectl get pods -n $NAMESPACE -l "app.kubernetes.io/instance=$RELEASE_NAME" -o jsonpath="{.items[0].metadata.name}")
          kubectl describe pod $POD_NAME -n $NAMESPACE
          kubectl logs $POD_NAME -n $NAMESPACE