name: Build & Deploy to Kubernetes

on:
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io
    IMAGE_NAME: ghcr.io/joelvin/taller-k8s-diplomado
    CHART_PATH: chart/taller-k8s-diplomado
    RELEASE_NAME: v1
    NAMESPACE: default

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Verificar conexión con Kubernetes
        run: |
          kubectl get nodes

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t $REGISTRY/${IMAGE_NAME}:${RELEASE_NAME} .

      - name: Push Docker image
        run: |
          docker push $REGISTRY/${IMAGE_NAME}:latest

      - name: Set up Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Deploy with Helm
        run: |
          helm upgrade --install mi-app ./chart/mi-app \
            --namespace default \
            --set image.repository=$REGISTRY/${IMAGE_NAME} \
            --set image.tag=latest
