name: Build & Deploy to Kubernetes

on:
  push:
    branches:
      - master

env:
  REGISTRY: docker.io
  IMAGE_NAME: joelvin/taller-k8s-diplomado
  CHART_PATH: ./charts/taller-k8s-diplomado
  RELEASE_NAME: v1
  NAMESPACE: default

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Debug variables
        run: |
          echo "RELEASE_NAME: $RELEASE_NAME"
          echo "CHART_PATH: $CHART_PATH"
          ls -la $CHART_PATH || echo "Chart path not found"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Compilar con Maven
        run: mvn clean package -DskipTests
        working-directory: ./

      - name: Login en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build imagen Docker
        run: |
          docker build -t $REGISTRY/$IMAGE_NAME:$RELEASE_NAME .

      - name: Push imagen Docker
        run: |
          docker push $REGISTRY/$IMAGE_NAME:$RELEASE_NAME

      - name: Set up kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config


      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: '3.14.0'


      - name: Deploy with Helm
        run: |
          helm upgrade --install $RELEASE_NAME $CHART_PATH \
            --namespace $NAMESPACE \
            --set image.repository=$REGISTRY/$IMAGE_NAME \
            --set image.tag=$RELEASE_NAME

      - name: Validar Despliegue
        run: |
          kubectl rollout status deployment/api-taller-k8s-diplomado -n default --timeout=60s
          kubectl get pods -n default
          kubectl logs <tu-pod> -n default
